// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAFM33J02lmfhNF_saASK3MUr6ezmw14',
    appId: '1:594792084059:web:0da6f3de86a978b274457e',
    messagingSenderId: '594792084059',
    projectId: 'fcms-e6bf7',
    authDomain: 'fcms-e6bf7.firebaseapp.com',
    databaseURL: 'https://fcms-e6bf7-default-rtdb.firebaseio.com',
    storageBucket: 'fcms-e6bf7.appspot.com',
    measurementId: 'G-3YCJLSFJ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYxzvv8iNccxJEMbLXtMUuFEo2Up9wIw',
    appId: '1:594792084059:android:699e658fcccb1ae074457e',
    messagingSenderId: '594792084059',
    projectId: 'fcms-e6bf7',
    databaseURL: 'https://fcms-e6bf7-default-rtdb.firebaseio.com',
    storageBucket: 'fcms-e6bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwHHVMitC1B3FRDFx0QGyYaTKHPtK6Pc',
    appId: '1:594792084059:ios:f1f466919d56e28974457e',
    messagingSenderId: '594792084059',
    projectId: 'fcms-e6bf7',
    databaseURL: 'https://fcms-e6bf7-default-rtdb.firebaseio.com',
    storageBucket: 'fcms-e6bf7.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwHHVMitC1B3FRDFx0QGyYaTKHPtK6Pc',
    appId: '1:594792084059:ios:f1f466919d56e28974457e',
    messagingSenderId: '594792084059',
    projectId: 'fcms-e6bf7',
    databaseURL: 'https://fcms-e6bf7-default-rtdb.firebaseio.com',
    storageBucket: 'fcms-e6bf7.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxFPU5kEZWKQz6thMOb7Rvx1L61baEPSU',
    appId: '1:594792084059:web:ae01b273aaf9494374457e',
    messagingSenderId: '594792084059',
    projectId: 'fcms-e6bf7',
    authDomain: 'fcms-e6bf7.firebaseapp.com',
    databaseURL: 'https://fcms-e6bf7-default-rtdb.firebaseio.com',
    storageBucket: 'fcms-e6bf7.appspot.com',
    measurementId: 'G-NG2PY5DVJ9',
  );
}
